package com.agychat.app.domain.model

/**
 * Represents a plan artifact generated by the agent.
 *
 * @property title Title of the plan.
 * @property markdownContent The detailed plan content in markdown.
 * @property metadata Optional metadata associated with the artifact.
 */
data class PlanArtifact(
    val title: String,
    val markdownContent: String,
    val metadata: ArtifactMetadata?
)
