package com.agychat.app.domain.model

/**
 * Represents a task artifact generated by the agent.
 *
 * @property title Title of the task.
 * @property markdownContent The detailed task description in markdown.
 * @property metadata Optional metadata associated with the artifact.
 */
data class TaskArtifact(
    val title: String,
    val markdownContent: String,
    val metadata: ArtifactMetadata?
)
