package com.agychat.app.domain.model

/**
 * Represents a walkthrough artifact generated by the agent.
 *
 * @property title Title of the walkthrough.
 * @property markdownContent The detailed walkthrough content in markdown.
 * @property metadata Optional metadata associated with the artifact.
 */
data class WalkthroughArtifact(
    val title: String,
    val markdownContent: String,
    val metadata: ArtifactMetadata?
)
